### PR TITLE
Added request command

### PR DESCRIPTION
**Pull request by byrnedo**
```
NAME:
   nats req - Usage: nats req [-s server url] [--ssl] [-t] [-w] <subject> <msg> 


USAGE:
   nats req [command options] [arguments...]

OPTIONS:
   -s "nats://localhost:4222"   The nats server URLs (separated by comma).
                Server Url must be in following format: nats://nats_user:nats_password@host:port or nats://host:port
   --ssl            Use Secure Connection
   -w "2s"          Duration to wait for response, eg '1s'
   -t               Display timestamps
   -r               Display raw output
```

### CODE REVIEW

**Comment by geofffranks** [comment]
Can you add some documentation in the readme for what this command is used for, and some examples?

**Comment by geofffranks** [comment]
@byrnedo ^^

**Comment by jhunt** [comment]
@byrnedo ^^

**Comment by byrnedo** [comment]
Hi, sorry, will try and get some time to

**Comment by alexanelli** [comment]
Hey @byrnedo have you had a chance to look into this?

**Comment by drnic** [comment]
@byrnedo today is a great day to finish up this PR so it can be merged :)

**Comment by byrnedo** [comment]
hahah @drnic, you persuaded me!! I added a bit of readme there now. Is that sufficient?

**Comment by drnic** [comment]
@byrnedo awesome!

**Pull request merged**
